version: '2.1'

services:
  pdb:
    image: postgres
    ports:
      - 15432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
  redis:
    image: redis
    ports:
      - 16379:6379
    volumes:
      - ./data/redis:/data
    command: redis-server --appendonly yes
